Add variable world height
MCHPR/MCHPRS pull request #119
Opened 2023-08-02 00:58 UTC by Paul1365972

Adds a new constant `PLOT_SECTIONS` to change the amount of sections per chunk.
Hope someone else can run the benchmark to make sure this doesn't negatively affect performance.

(Also fixes a spelling mistake and some minor compiler warnings)

2023-08-02 03:11 UTC, StackDoubleFlow requested changes

2023-08-02 03:11 UTC, StackDoubleFlow commented on crates/core/src/world/storage.rs
> +            6 => fast_arr_idx::<6>,
5 and 6 are not valid values here, so they should not be included. The number of bits per block goes from 4 to 9 when using the section palette, then jumps to 15 when using the global palette. That means the set of possible bits per block values are `{4, 5, 6, 7, 8, 9, 15}`. Dividing 64 by these values to gives you the number of entries that fit in a 64 bit value: `{16, 12, 10, 9, 8, 7, 4}`. Although looking at [wiki.vg](https://wiki.vg/Chunk_Format#:~:text=the%20blue%20lines.-,Global%20and%20section%20palettes,-Illustration%20of%20an), vanilla seems to not go up to 9 bits per block when using the section palette, so it might be worth looking into this further, but that's outside the scope of this PR.

2023-08-02 03:11 UTC, StackDoubleFlow commented on crates/save_data/src/plot_data.rs
> +pub struct PlotData<const SECTIONS: usize> {
The name `SECTIONS` doesn't really make sense in the context of plot data. Maybe something like `NUM_CHUNKS_Y` would better convey the message. Documenting it could also help if we can't think of a good name.

2023-08-02 03:11 UTC, StackDoubleFlow commented on crates/core/src/world/storage.rs
> +        let sections = unsafe { std::mem::transmute(sections) };
Using unsafe code to do this is pretty terrible. Try using [`std::array::from_fn`](https://doc.rust-lang.org/std/array/fn.from_fn.html) instead.

2023-08-02 03:11 UTC, StackDoubleFlow commented on crates/core/src/world/storage.rs
> +use crate::plot::{PLOT_BLOCK_HEIGHT, PLOT_SECTIONS};
`crate` includes are lumped in with the rest for now.

2023-08-02 03:11 UTC, StackDoubleFlow commented on crates/core/src/world/storage.rs
> +        const HEIGHTMAP_BITS: u8 = (32 - (PLOT_BLOCK_HEIGHT as u32 + 1).leading_zeros()) as u8;
According to [wiki.vg](https://wiki.vg/Chunk_Format#:~:text=It%27s%20encoded%20as%20a%20compacted%20long%20array%20with%20256%20entries%20at%209%20bits%20per%20entry%20totalling%2037%20longs.), shouldn't this always be 9?

2023-08-02 09:17 UTC, Paul1365972 commented on crates/core/src/world/storage.rs
> +        const HEIGHTMAP_BITS: u8 = (32 - (PLOT_BLOCK_HEIGHT as u32 + 1).leading_zeros()) as u8;
Seems like [wiki.vg](https://wiki.vg/Protocol#Chunk_Data_and_Update_Light:~:text=with%20the%20number%20of%20bits%20per%20entry%20varying%20depending%20on%20the%20world%27s%20height%2C%20defined%20by%20the%20formula%20ceil(log2(height%20%2B%201)))) is inconsistent here, the value of `9 bits per entry` is only correct when dealing with worlds of heights `256` to `496` (`16` to `31` Sections). This is also why I exposed the remaining `bitbuffer` values, as the heightmap uses the same padded long array strategy.

2023-08-02 09:28 UTC, Paul1365972 commented on crates/save_data/src/plot_data.rs
> +pub struct PlotData<const SECTIONS: usize> {
Yeah wasn't happy with the naming as well `NUM_CHUNKS_SECTIONS` and `NUM_SECTIONS` is a bit of a mouthful, but at least self documenting.
We could also consider removing the generic stuff altogether and using a vec instead of an array for `ChunkData`, but I am unsure if this would impact performance.
It would also be interesting to make each section only allocate when needed, to combat the high memory consumption of bigger plots, but again performance. That would need some testing.

2023-08-02 09:28 UTC, Paul1365972 commented on crates/core/src/world/storage.rs
> +        let sections = unsafe { std::mem::transmute(sections) };
Fixed

2023-08-02 09:32 UTC, Paul1365972 commented on crates/core/src/world/storage.rs
> +            6 => fast_arr_idx::<6>,
Is there any reason this check is important to fail for the other numbers? If yes, adding asserts before calling `BitBuffer::create` seems just as valid. The remaining numbers are important for the variable bit length heightmap. See bottom most comment.

2023-08-03 04:52 UTC, StackDoubleFlow commented on crates/core/src/world/storage.rs
> +            6 => fast_arr_idx::<6>,
It's not important, but I do strive for correctness. The asserts are not necessary. After reading the other comment, I see now why I had 9 bits per entry there, and why the new values are necessary.

2023-08-03 04:54 UTC, StackDoubleFlow commented on crates/save_data/src/plot_data.rs
> +pub struct PlotData<const SECTIONS: usize> {
Right, I've also thought about just using a Vec there. It would require a world format change though, and I've been thinking about some pretty major changes to the way I save worlds, so it might be worth lumping it in with those changes later.

2023-08-03 04:55 UTC, StackDoubleFlow approved these changes

2023-08-03 05:17 UTC, StackDoubleFlow commented
Looks good! Please rebase then I'll merge.

2023-08-05 00:38 UTC, merged