Render filter optimization
MCHPR/MCHPRS pull request #120
Opened 2023-08-02 15:50 UTC by Paul1365972

Adds a command `/togglerenderfilter` to toggle the render filter optimization (per plot).
This stops the server from sending non-IO redstone component block changes to the client.
This commit also adds a few more commands to the auto complete graph.

Considerations:
- After deactivating the filter all affected redstone components are still in a desynchronized state. Maybe invert the filter and resend all "missed" changes
- Using a build script and perfect hash functions may be a bit overkill and add unnecessary code complexity (Move to different/separate crate?)
- This setting could make more sense as an per player option, this could possibly be a bit trickier to implement

2023-08-03 05:04 UTC, StackDoubleFlow commented
Another thing to consider is that the `--io-only` flag in redpiler does much the same thing. It feels odd having this be a completely separate concept from that. I think it would be easier if we could unify these across the different backends. Maybe we could have it so that if the render filtering is enabled, it automatically sets that flag on redpiler compiles?

2023-08-03 05:12 UTC, StackDoubleFlow requested changes

2023-08-03 05:12 UTC, StackDoubleFlow commented on crates/core/build.rs
> +            //    && wire.west == RedstoneWireSide::None => {}
Commented out code?

2023-08-03 05:12 UTC, StackDoubleFlow commented on crates/core/build.rs
> +            | Block::Observer { .. }
Observers don't actually change state. Right now they're only used for redstone wire redirection, so they don't have to be blacklisted.

2023-08-03 05:12 UTC, StackDoubleFlow commented on crates/core/src/plot/commands.rs
> +                    // TODO: Resend all skipped block changes
Here, as a temporary solution, I'd just resend the chunks to the player. Send them a chat message informing them of so, and then call `update_view_pos_for_player` with `force_load` set to true.

2023-08-03 11:12 UTC, Paul1365972 commented
Seems like I missed the --io-only flag.
I believe filtering non-IO updates without compiling is nonetheless a useful feature, at least I am currently using it.
Considering that the two concepts are so similar I'll rename the command to `/toggleioonly` and auto activate the --io-only flag when running the `/redpiler compile` command as you suggested.

2023-08-03 11:15 UTC, Paul1365972 commented on crates/core/src/plot/commands.rs
> +                    // TODO: Resend all skipped block changes
After calling `update_view_pos_for_player ` everything should be in sync and I wouldn't need to inform the user that stuff may look wrong, correct? Or did you mean a general "[...] Reloading chunks..." message?

2023-08-03 11:16 UTC, Paul1365972 commented on crates/core/build.rs
> +            | Block::Observer { .. }
I'll just keep them listed anyways to make sure nobody forgets them later, shouldn't make a difference

2023-08-03 13:01 UTC, Paul1365972 commented
I added another related commit to this PR. It unifies the front- and backends understanding of what a input or output component is. This should help keep the logical inconsistencies at bay and make future optimization passes easier to implement and maintain.
This however sadly couples the redpiler's logic to the build script. However I tried to minimize the interaction surface to a minimum, just in case the redpiler should ever be extracted into its own crate.

Since the logic got more complicated, should these generated sets be moved from the plot/mod.rs file into their own? Perhaps a `constants.rs` file with other constants, that are currently still scattered across the code base, would be useful in the future.

2023-08-09 14:16 UTC, Paul1365972 commented
Closing in favor of #123

2023-08-09 14:16 UTC, closed without merging