Duplicate signal strength to all outputs
MCHPR/MCHPRS pull request #129
Opened 2023-10-15 11:43 UTC by BramOtte

We duplicate the signal strength of a component to all outputs, so we can get the input signal strength without having to fetch the inputs each time. Additionally by having separate buckets for each signal strength the combined input strength is calculated with just a few u128 instructions instead of having to loop over all the input.

2023-11-23 20:38 UTC, Paul1365972 commented
Wow wouldn't have thought that such huge performance improvements were still possible. Confirmed similar performance increases (37-40% on my windows intel i7-6700HQ machine).
However this change would hard lock this project to never support HSS (Signal strengths above 15, in vanilla 897 is the limit iirc), just something to consider.
By the way, did you somehow verify that redstone behaves the same? While testing with this patch there are about 1% less redstone ticks. Just making sure, but most likely nothing to worry about since there would probably be larger discrepancies if something actually went wrong.
Also probably a good idea to add a sanity check and panic if either the default or side input has more than 255 input connections.

2023-11-24 17:13 UTC, Paul1365972 commented
Btw on [line 272 of `direct.rs`](https://github.com/MCHPR/MCHPRS/pull/129/files#diff-76dbc7f67d09f68716c86ffebeea3412c537bad28576cc15a8950b0547e37257R272) there is one constant 16 that should have also been replaced by `Self::NUM_QUEUES`.

2023-12-05 23:11 UTC, StackDoubleFlow reviewed
Great work! I'm happy to merge this after a quick `cargo fmt`.

2023-12-05 23:11 UTC, StackDoubleFlow commented on crates/core/src/redpiler/backend/direct.rs
> +impl ForwardLink {
nit: there's usually a newline between blocks (at least in this codebase)

2023-12-05 23:11 UTC, StackDoubleFlow commented on crates/core/src/redpiler/backend/direct.rs
> +    pub fn node(self) -> NodeId {
same with functions

2023-12-05 23:11 UTC, StackDoubleFlow commented on crates/core/src/redpiler/backend/direct.rs
> +const INPUT_MASK: u128 = u128::from_ne_bytes([0, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255]);
nit: maybe a better name being `BOOL_INPUT_MASK`?
Better to be specific since it's module scoped.

2023-12-05 23:28 UTC, BramOtte commented
> Great work! I'm happy to merge this after a quick `cargo fmt`.

alright I'l do that there is also one other minor fix I will add shortly
Also a question when I do cargo fmt another parts of the code also changed I assume I should not include these in my pull request?

2023-12-05 23:32 UTC, StackDoubleFlow commented
It's normally good practice not to, but I'll allow it in this case. Eventually I'd like to have CI fail if code isn't formatted properly so that it stops seeping into the repo.

2023-12-05 23:36 UTC, BramOtte commented
alright that should be it then I also changed ForwardLink::new and tested it with chungus2 and all is fine and well.
previously it would crash on non-optimized builds because ss was too large so I made it clamp instead of crash.
It might also indicate that something else in the code is going wrong but for now this will suffice.

2023-12-06 01:22 UTC, Paul1365972 commented
Maybe just putting a `graph.retain_edges(|g, edge| g[edge].ss <= 15);` at the top of the compile function (or in a compiler pass) would make sense here as well.

2023-12-08 01:53 UTC, StackDoubleFlow commented
> Maybe just putting a `graph.retain_edges(|g, edge| g[edge].ss <= 15);` at the top of the compile function (or in a compiler pass) would make sense here as well.

Like in the [ClampWeights](https://github.com/MCHPR/MCHPRS/blob/master/crates/core/src/redpiler/passes/clamp_weights.rs) pass?

2023-12-08 01:53 UTC, StackDoubleFlow commented
Please rebase and I'll merge

2023-12-08 02:28 UTC, Paul1365972 commented
You're right, completly forgot about that pass. In that case I think making the ClampWeights pass mandatory (or just merging it into the InputSearch pass) and keeping the assert would be a good idea, not that it will make much of a difference.

2023-12-08 19:57 UTC, BramOtte commented
> Please rebase and I'll merge

I don't really know how rebase works so I merged it instead.
From what I understand how rebase works is it is basically equivilant to merging on master.
So I created a new branch from the current state of master: https://github.com/BramOtte/MCHPRS/tree/duplicate-signal-strength-rebase
aswell and merged my changes onto that incase you find that more convenient.

2023-12-11 16:20 UTC, StackDoubleFlow commented
Your previous merge commit was empty, there are still conflicts with master.

2023-12-11 18:07 UTC, BramOtte commented
I do not understand what exactly went wrong, but I got the rebase to work, turnsout I just had to force push to make it work.
So you should be able to merge with no issues now

2023-12-14 16:52 UTC, StackDoubleFlow requested changes

2023-12-14 16:52 UTC, StackDoubleFlow commented on crates/core/src/redpiler/backend/direct.rs
> +        let mut side_inputs = NodeInput {ss_counts: [0; 16]};
nit: formatting error, run `cargo fmt`

(Hopefully this won't be a problem with future PRs since CI will catch it)

2023-12-14 17:01 UTC, StackDoubleFlow approved these changes

2023-12-14 17:03 UTC, merged