Fix and simplify `world::for_each_block_optimized`
MCHPR/MCHPRS pull request #169
Opened 2024-12-25 19:34 UTC by verglasz

First time contributor, so please let me know if I'm doing anything wrong.

I was looking at the source for no particular reason at all and decided to take a stab at this:
https://github.com/MCHPR/MCHPRS/blob/76b9b8cf575ee4419eca5c2cd9dac56405a2cafe/crates/world/src/lib.rs#L84
finding a bug in the process.

This PR replaces the duplicated implementation of `for_each_block_optimized` and
`for_each_block_mut_optimized` in the `mchprs_world` crate with a simpler implementation
that abstracts the iteration logic.

Also this adds tests for the iteration logic and for the `for_each_block_optimized` function
(which is how I realised that the current implementation had a bug that could lead
to some non-air block being skipped, see #168 for more details); let me know if
they're too verbose or if there should be other cases covered.

With the new implementation #168 should be fixed, since the new iteration special-cases
the bounding box boundaries and otherwise checks the block in batches corresponding
to chunk sections.

2024-12-26 21:36 UTC, Paul1365972 commented
Good catch, I initally wrote this code to only work for entire plots, but I seems like I somehow forgot that invariant when making it more generic, thank you very much!
The new code might perform worse as we call `block_pos_in_chunk_section_between` for each chunk, instead of handling the edge cases separately, but I would guess this is negligible.

2025-01-03 00:00 UTC, verglasz commented
Yeah, I think it’d need benchmarking to see what’s the best performant approach for that, couldn’t think of anything particularly clever to do around it but it may be worth seeing if checking whether we’re in one of the chunk sections on the edge or maybe iterating over those separately from the interior do perform better.

2025-08-03 20:56 UTC, StackDoubleFlow requested changes
Sorry for the late reply, and thanks for taking the time to fix this issue. Just left a small comment, but overall LGTM

2025-08-03 20:56 UTC, StackDoubleFlow commented on crates/world/src/lib.rs
> +            todo!()
For these functions, maybe it would be better to use `unimplemented!()` instead, as it's not clear that we would ever need to implement these.

2025-08-10 17:40 UTC, verglasz commented on crates/world/src/lib.rs
> +            todo!()
Good point, I changed it and added a comment.

2025-10-21 10:23 UTC, merged