Fix #9
MCHPR/MCHPRS pull request #25
Opened 2020-12-20 02:34 UTC by garentyler

Get the name from the db based on uuid before printing the output of the command.

2020-12-20 23:40 UTC, StackDoubleFlow requested changes

2020-12-20 23:40 UTC, StackDoubleFlow commented on src/plot/database.rs
> +pub fn get_name(uuid: String) -> Option<String> {
`get_name` is a little bit vague. How about something like `get_cached_username`?

2020-12-20 23:40 UTC, StackDoubleFlow commented on src/plot/commands.rs
> +                    self.players[player].send_system_message(&format!("Plot owner is: {}", database::get_name(owner).unwrap()));
While it shouldn't be possible for the player name to not be cached in the database, it would be better to not crash in this scenario. Maybe instead of using `unwrap`, just use the plain uuid if None is returned.

2020-12-21 00:37 UTC, garentyler commented on src/plot/commands.rs
> +                    self.players[player].send_system_message(&format!("Plot owner is: {}", database::get_name(owner).unwrap()));
Maybe `.unwrap_or("unknown")` or something similar to provide a default?

2020-12-21 00:38 UTC, garentyler commented on src/plot/database.rs
> +pub fn get_name(uuid: String) -> Option<String> {
`get_cached_username` sounds good, I'll rename it

2020-12-28 07:33 UTC, StackDoubleFlow commented on src/plot/commands.rs
> +                    self.players[player].send_system_message(&format!("Plot owner is: {}", database::get_name(owner).unwrap()));
How about using the uuid if the username isn't found?

2021-01-06 22:15 UTC, StackDoubleFlow approved these changes

2021-01-06 22:15 UTC, StackDoubleFlow commented
Looks great, thanks!

2021-01-06 22:17 UTC, merged