Add /plot visit [player] command
MCHPR/MCHPRS pull request #38
Opened 2021-05-07 04:03 UTC by tyler569

This adds the ability to visit a player's claimed plot.

To accomplish this, I add a new function to `database` that can find a
plot's x, z coordinates by name, a new option to handle_plot_command,
and new entries to the completion tree.

I tested this to work for multiple players, and it does not break if
someone has multiple plots, though you will always only go to one.

2021-05-07 16:27 UTC, AL1L commented
How does it handle if a player has more than one plot? It just get the first one it finds?

2021-05-07 16:29 UTC, AL1L approved these changes
Looks good to me

2021-05-07 16:29 UTC, AL1L commented on src/plot/commands.rs
> +            // 40: /p middle
Out of scope ;) I'll let it slide haha

2021-05-07 16:33 UTC, AL1L commented on src/plot/commands.rs
> +                let plot = database::get_owned_plot(args[0]);
Can you validate that they put enough args?

2021-05-07 16:33 UTC, AL1L requested changes

2021-05-07 16:33 UTC, AL1L commented on src/plot/commands.rs
> +                let plot = database::get_owned_plot(args[0]);
Can you validate that they put enough args?

2021-05-08 00:14 UTC, tyler569 commented
Currently, if a player has more than one plot `/p v player` will take you to the first one SQLite returns, likely the first one they claimed. We could make it any with `/p v player [number]` or something and some more complicated SQL, but I see that more as an improvement for later than super necessary. I can work on it if people feel differently though.

I've updated the branch to check argument count.

2021-05-08 01:13 UTC, StackDoubleFlow approved these changes

2021-05-09 17:31 UTC, merged