Some random fixes + README update
MCHPR/MCHPRS pull request #71
Opened 2022-07-16 15:24 UTC by Olek47

my first pull request btw

2022-07-16 18:54 UTC, BananaSquares commented
Looks pretty good but for future reference its better to split different changes into multiple pull requests. Also not 100% sure about changing the no wires flag name given people are probably used to the current name.

2022-07-16 18:57 UTC, Olek47 commented
I changed it because its named "- optimize" on scoreboard.

2022-07-22 15:33 UTC, StackDoubleFlow requested changes
There's a lot going on here. As @Olek47 noted, it would have been better to have these changes in separate pull requests. 

Could you also run `cargo fmt` just to keep the formatting consistent?

2022-07-22 15:33 UTC, StackDoubleFlow commented on README.md
> +| `/plot tp [x] [z]` | `/p tp` | Teleports you to the plot at `[x] [y]`. Supports relative coordinates. |
Since the `tp` subcommand is the same here, I would recommend changing the alias to `None` instead.

2022-07-22 15:33 UTC, StackDoubleFlow commented on src/chat.rs
> +    // SuggestCommand,
I'm thinking about moving the chat stuff into its own library in the future, so I'd prefer if these were left alone.

2022-07-22 15:33 UTC, StackDoubleFlow commented on src/chat.rs
> -
Same with this.

2022-07-22 15:33 UTC, StackDoubleFlow commented on src/plot/commands.rs
> +                            .send_error_message("pls stop");
Maybe send something better here :P

2022-07-22 15:45 UTC, Olek47 commented on README.md
> +| `/plot tp [x] [z]` | `/p tp` | Teleports you to the plot at `[x] [y]`. Supports relative coordinates. |
Oh ok, I just realized thats the same subcommand.

2022-07-22 15:50 UTC, Olek47 commented on src/plot/commands.rs
> +                            .send_error_message("pls stop");
I'll change it to something like `You can't set your speed to NaN or -NaN`.

2022-07-22 15:59 UTC, Olek47 commented on src/chat.rs
> -
Can I left it as a comment?

2022-07-22 16:12 UTC, StackDoubleFlow commented on src/chat.rs
> -
Sure

2022-07-22 17:59 UTC, StackDoubleFlow approved these changes

2022-07-22 17:59 UTC, merged